---
title: "Task 1"
format: html
editor: visual
---

## Day 2 activities

```{r}
vec_1 <- c(2, 5, 9, 10, 8, 12, 1, 0)

# check class
class(vec_1)
# check variable type
typeof(vec_1)
# access 3rd element and store
vec_1_e3 <- vec_1[3]
# access 1st element
vec_1_e1 <- vec_1[1]
# access 5th through 7th elements
vec_1_e5to7 <- vec_1[5:7]
# reassign vec_1 as character
vec_1_char <- as.character(vec_1)
class(vec_1_char)
vec_1_char
# create another vector with named elements
vec_2 <- c(town = "Santa Barbara", location = "Rincon", swell = "south")
class(vec_2)
length(vec_2)
# access 2nd element
vec_2_e2 <- vec_2[2]
```

## create a data frame in R, index

```{r}
# create a data frame
df_1 <- data.frame(region = c("A", "B", "A", "D"),
                   species = c("otter", "great white", "sea lion", "gray whale"),
                   count = c(12, 2, 36, 6))

class(df_1)
# find the class of the species column
class(df_1$species)

# find maximum value of the count column

max_count <- max(df_1$count)
```

## part 3: wild data

```{r}

```
