---
title: "wild data"
format: html
editor: visual
execute: 
  warning: false
---

### part 2: wild data

```{r}
library(tidyverse)
library(here)
library(janitor)
```

```{r}
# read in the wild data .csv
mack_verts <- read_csv(here("data", "AS00601.csv")) %>% 
  clean_names()
```

```{r}
# store 5th value in "weight" 
mc_wt_5 <- mack_verts$weight[5]
mc_wt_5a <- pluck(mack_verts, "weight", 5)

# store 8th-20th value in length1
mc_length_8_20 <- mack_verts$length1[8:20]
# this doesn't work- pluck wants to pull a single value, not a data structure
# mc_length_8_20a <- pluck(mack_verts, "length1", 8:20)

# store everything in "sampledate" as a vector
mc_dates <- mack_verts$sampledate
```

## make a salamander subset

```{r}
# create a subset that only contains observations for pacific giant salamanders

mc_salamanders <- mack_verts %>% 
  filter(species == "DITE")
```

## make a scatterplot of salamander length x weight

```{r}
salamander_size <- ggplot(data = mc_salamanders, 
                          aes(x = length1,
                              y = weight)) +
  geom_point(color = "purple", alpha = .5) +
  labs(title = "Salamander length versus weight",
       x = "length",
       y = "weight", caption = "Datasource: USFS Pacific Northwest Research Station") +
  theme_dark()

salamander_size

ggsave(filename = here("figures", "salamander_size.png"), 
       plot = salamander_size)
```

### make a cutthroat plot

```{r}
mc_cutthroat <- mack_verts %>% 
  filter(species == "ONCL")
```

```{r}
cutthroat_size <- ggplot(data = mc_cutthroat, 
                         aes(x = length1,
                             y = weight)) + 
  geom_point(aes(color = reach),
             alpha = .8) +
  theme_grey() +
  labs(title = "cutthroat length vs weight",
       x = "length",
       y = "weight",
       caption = "Datasource: USFS Pacific Northwest Research Station") +
  facet_wrap(~reach)

cutthroat_size

ggsave(filename = here("figures", "cutthroat_size.png"),
       plot = cutthroat_size)
```
